/**
 * Deterministic, read-only production-readiness assessment (Phase 1).
 *
 * Every finding below is grounded in an existing repository artifact (route
 * registry, capability registries, ADRs, test suites, release docs). Where no
 * evidence exists the finding is explicitly `not-assessed` or `unavailable`.
 * Nothing here computes a score; the UI renders counts and states only.
 */
import type { ReadinessFinding } from './types';

/**
 * The Phase 1 evidence base. Static by design: the supervisor reads the same
 * artifacts a reviewer would, and the contract test fails if a finding loses
 * its required fields or claims a pass without an evidence reference.
 */
export const READINESS_FINDINGS: ReadinessFinding[] = [
  {
    id: 'security-rls-tenancy',
    category: 'security',
    title: 'Row-level security and grants on public tables',
    status: 'pass',
    severity: 'blocker',
    evidenceSource: 'Database RLS/GRANT migration pattern and auth RLS suite',
    evidenceRef: 'tests/database/01_auth_rls_suite.sh',
    affectedRoutes: ['/*'],
    affectedFiles: ['supabase/migrations', 'src/auth/permissions.ts'],
    recommendedAction: 'Keep the migration grant-before-policy pattern mandatory in review.',
    ownerPersona: 'compliance-risk',
    verificationMethod: 'Run the auth/RLS SQL suite against a clean replay.',
  },
  {
    id: 'security-fail-closed-authorization',
    category: 'security',
    title: 'Fail-closed authorization on protected routes',
    status: 'pass',
    severity: 'blocker',
    evidenceSource: 'Route guards and permission model',
    evidenceRef: 'src/routing/PermissionRouteGuard.tsx',
    affectedRoutes: ['/analytics', '/deploy', '/compliance', '/settings/ai', '/teams'],
    affectedFiles: ['src/AuthenticatedShell.tsx', 'src/routing/AdminRouteGuard.tsx'],
    recommendedAction: 'Extend PermissionRouteGuard to any new privileged route at mount time.',
    ownerPersona: 'engineer',
    verificationMethod: 'Route registry contract test plus unauthenticated deep-link probes.',
  },
  {
    id: 'tenancy-active-org',
    category: 'tenancy',
    title: 'Active organization resolved through server RPC only',
    status: 'pass',
    severity: 'blocker',
    evidenceSource: 'Tenant authority remediation (P1)',
    evidenceRef: 'src/auth/activeOrgBootstrap.ts',
    affectedRoutes: ['/builder', '/account/settings'],
    affectedFiles: ['src/contexts/RBACContext.tsx', 'supabase/functions/builders-create'],
    recommendedAction: 'Audit remaining write paths for implicit tenant fallback.',
    ownerPersona: 'tenant-admin',
    verificationMethod: 'Tenancy-hardening unit suite plus builders-create 403 probe.',
  },
  {
    id: 'tenancy-unresolved-recovery',
    category: 'tenancy',
    title: 'Recovery surface for unresolved tenant state',
    status: 'pass',
    severity: 'medium',
    evidenceSource: 'RBAC resolution states and Account Settings recovery guidance',
    evidenceRef: 'src/pages/account/Settings.tsx',
    affectedRoutes: ['/account/settings', '/teams/access-control'],
    affectedFiles: ['src/ApprovedUserRouter.tsx'],
    recommendedAction: 'Add an automated tenant-unresolved journey test.',
    ownerPersona: 'tenant-admin',
    verificationMethod: 'Sign in with a membership-less account and confirm recovery guidance renders.',
  },
  {
    id: 'auth-approval-and-hydration',
    category: 'auth',
    title: 'Approval gate and session hydration before redirect',
    status: 'pass',
    severity: 'high',
    evidenceSource: 'Admin approval system and auth-route hydration gate (P1)',
    evidenceRef: 'src/AuthenticatedSessionApp.tsx',
    affectedRoutes: ['/login', '/dashboard', '/*'],
    affectedFiles: ['src/pages/auth', 'src/pages/PendingApproval.tsx'],
    recommendedAction: 'Keep hydration-gate regression coverage alongside any auth routing change.',
    ownerPersona: 'engineer',
    verificationMethod: 'Verified-session reload test: no bounce to /login.',
  },
  {
    id: 'data-provenance-model',
    category: 'data-provenance',
    title: 'Canonical provenance model on rendered metrics',
    status: 'pass',
    severity: 'high',
    evidenceSource: 'ADR-0004 / ADR-0006 and provenance envelope types',
    evidenceRef: 'src/lib/provenance/types.ts',
    affectedRoutes: ['/dashboard', '/analytics', '/evidence/overview'],
    affectedFiles: ['src/lib/provenance', 'src/telemetry'],
    recommendedAction: 'Extend provenance envelopes to remaining legacy KPI panels.',
    ownerPersona: 'data-scientist',
    verificationMethod: 'Truth-in-UI suite: every KPI renders a provenance tag.',
  },
  {
    id: 'data-live-telemetry-feed',
    category: 'data-provenance',
    title: 'Measured production facility telemetry (DCIM/BMS)',
    status: 'unavailable',
    severity: 'high',
    evidenceSource: 'No production feed is connected; rendered values are simulated or demo fixtures',
    evidenceRef: 'src/pages/IntelligenceDashboard.tsx',
    affectedRoutes: ['/analytics', '/dashboard'],
    affectedFiles: ['src/telemetry/useFacilityTelemetry.ts', 'src/runtime/mqtt'],
    recommendedAction: 'Connect a validated customer telemetry source before any measured-data claim.',
    ownerPersona: 'facility-operator',
    verificationMethod: 'Source connection state reaches connected with non-stale payloads.',
  },
  {
    id: 'runtime-accelerated-ai',
    category: 'runtime',
    title: 'NVIDIA DSX / Omniverse runtime integration',
    status: 'unavailable',
    severity: 'blocker',
    evidenceSource: 'DSX capability registry records alignment only; no vendor runtime executes',
    evidenceRef: 'src/config/dsxCapabilityRegistry.ts',
    affectedRoutes: ['/admin/accelerated-ai-capabilities', '/twin-preview'],
    affectedFiles: ['docs/dsx-alignment/aura-dsx-capability-map.md'],
    recommendedAction: 'Treat DSX/runtime availability as unavailable until runtime evidence exists; keep claims to alignment wording.',
    ownerPersona: 'engineer',
    verificationMethod: 'Runtime observation evidence recorded in the capability registry.',
  },
  {
    id: 'runtime-simulation',
    category: 'runtime',
    title: 'Deterministic simulation engine',
    status: 'pass',
    severity: 'medium',
    evidenceSource: 'Simulation engine with durable runs; results are simulated, never measured',
    evidenceRef: 'src/simulation',
    affectedRoutes: ['/simulation', '/deploy'],
    affectedFiles: ['src/engines', 'src/workspace/AuraWorkspace.tsx'],
    recommendedAction: 'Keep SIMULATED qualifiers on every surface that renders run output.',
    ownerPersona: 'data-scientist',
    verificationMethod: 'Simulation engine unit tests and run provenance records.',
  },
  {
    id: 'integrations-multicloud',
    category: 'integrations',
    title: 'Multicloud AI runtimes (AWS, Azure, Google, OCI, on-prem)',
    status: 'not-assessed',
    severity: 'medium',
    evidenceSource: 'No connected cloud AI runtime evidence exists in the repository',
    evidenceRef: null,
    affectedRoutes: ['/manage/integrations', '/settings/ai'],
    affectedFiles: ['infra/aws/publication-architecture.md'],
    recommendedAction: 'Define the first provider integration boundary and record connection evidence before claiming support.',
    ownerPersona: 'implementation-partner',
    verificationMethod: 'Connection handshake evidence plus a passing provider contract test.',
  },
  {
    id: 'integrations-managed-ai-contract',
    category: 'integrations',
    title: 'Managed AI exposes stable response profiles only',
    status: 'pass',
    severity: 'high',
    evidenceSource: 'Managed AI contract remediation (P1): raw provider/model keys removed from the browser contract',
    evidenceRef: 'src/lib/llm/responseProfiles.ts',
    affectedRoutes: ['/settings/ai', '/builder'],
    affectedFiles: ['src/stores/wizardBuilderStore.ts', 'src/services/builderService.ts'],
    recommendedAction: 'Reject legacy provider/model keys server-side on profile save.',
    ownerPersona: 'engineer',
    verificationMethod: 'Contract test: UI and stored payloads carry balanced/fast/reasoning only.',
  },
  {
    id: 'observability-runtime-monitoring',
    category: 'observability',
    title: 'Runtime monitoring and alerting pipeline',
    status: 'gap',
    severity: 'medium',
    evidenceSource: 'Client-side monitoring adapter exists; no production observability backend is evidenced',
    evidenceRef: 'src/monitoring/runtimeMonitoring.ts',
    affectedRoutes: ['/dashboard'],
    affectedFiles: ['src/monitoring'],
    recommendedAction: 'Select and connect an observability backend; record availability evidence.',
    ownerPersona: 'engineer',
    verificationMethod: 'Synthetic event visible end-to-end in the observability backend.',
  },
  {
    id: 'resilience-dr',
    category: 'resilience',
    title: 'Disaster recovery and availability evidence',
    status: 'not-assessed',
    severity: 'high',
    evidenceSource: 'Rollback runbook exists, but no DR exercise or availability evidence is recorded',
    evidenceRef: 'docs/release/rollback-runbook.md',
    affectedRoutes: [],
    affectedFiles: ['docs/release/rollback-runbook.md'],
    recommendedAction: 'Run and record a DR/restore exercise before enterprise commitments.',
    ownerPersona: 'executive',
    verificationMethod: 'Signed DR exercise report with measured recovery time.',
  },
  {
    id: 'ux-shared-visual-system',
    category: 'ux-accessibility',
    title: 'Shared workspace visual system on primary surfaces',
    status: 'pass',
    severity: 'medium',
    evidenceSource: 'Workspace visual-system contract test across primary pages',
    evidenceRef: 'tests/unit/workspace-visual-system-contract.test.ts',
    affectedRoutes: ['/dashboard', '/blueprint/default', '/simulation', '/deploy', '/help'],
    affectedFiles: ['src/components/workspace-system'],
    recommendedAction: 'Migrate remaining legacy page shells (Teams, Marketplace) to the shared system.',
    ownerPersona: 'customer-success',
    verificationMethod: 'Contract test enumerating primary surfaces stays green.',
  },
  {
    id: 'ux-legacy-visual-debt',
    category: 'ux-accessibility',
    title: 'Legacy page shells outside the shared visual system',
    status: 'gap',
    severity: 'low',
    evidenceSource: 'Read-only route audit: several secondary pages still render bespoke headers',
    evidenceRef: 'docs/audit/full-ux',
    affectedRoutes: ['/teams', '/marketplace', '/app/agents'],
    affectedFiles: ['src/pages/Teams.tsx', 'src/pages/Marketplace.tsx'],
    recommendedAction: 'Schedule atomic visual-parity passes after P1 correctness work completes.',
    ownerPersona: 'customer-success',
    verificationMethod: 'Visual-system contract test extended to the migrated pages.',
  },
  {
    id: 'qualification-gate',
    category: 'qualification',
    title: 'verify:fast qualification gate (typecheck, lint, unit, build)',
    status: 'pass',
    severity: 'high',
    evidenceSource: 'Testing strategy and package gate wiring',
    evidenceRef: 'docs/AURA-DC-Testing-Strategy.md',
    affectedRoutes: [],
    affectedFiles: ['package.json', 'vitest.config.ts'],
    recommendedAction: 'Keep failure counts honest; never delete or skip tests to pass a gate.',
    ownerPersona: 'engineer',
    verificationMethod: 'verify:fast exit code 0 on the exact candidate SHA.',
  },
  {
    id: 'release-fingerprint',
    category: 'release',
    title: 'Release fingerprint attestation (/release.json)',
    status: 'pass',
    severity: 'high',
    evidenceSource: 'Release source stamping and post-publish attestation practice',
    evidenceRef: 'scripts/stamp-release-source.mjs',
    affectedRoutes: ['/release.json'],
    affectedFiles: ['release-source.json', 'docs/release/PRODUCTION_SOURCE_OF_TRUTH.md'],
    recommendedAction: 'Automate post-publish fingerprint comparison in CI.',
    ownerPersona: 'implementation-partner',
    verificationMethod: 'Published /release.json sha equals the merged Git SHA.',
  },
  {
    id: 'release-post-publish-smoke',
    category: 'release',
    title: 'Continuous post-publish smoke verification',
    status: 'gap',
    severity: 'medium',
    evidenceSource: 'Smoke checks are performed manually per release; no continuous evidence exists',
    evidenceRef: 'docs/dsx-alignment/published-verification.md',
    affectedRoutes: ['/dashboard', '/login'],
    affectedFiles: ['.github/workflows'],
    recommendedAction: 'Wire an automated post-publish smoke suite for high-value authenticated routes.',
    ownerPersona: 'implementation-partner',
    verificationMethod: 'Scheduled workflow evidence for the last N releases.',
  },
];

export function buildReadinessAssessment(): ReadinessFinding[] {
  // Phase 1 returns the deterministic evidence base unchanged.
  return READINESS_FINDINGS.map((finding) => ({ ...finding }));
}
