/**
 * Operating state shared by the persistent state bar, provenance drawers
 * and exports. Mode truth comes from the capability registry.
 */
import { CAPABILITIES } from './registry';

export type OperatingMode = 'SIMULATED' | 'REPLAYED' | 'LIVE' | 'NVIDIA_DSX';

export interface OperatingModeMeta {
  mode: OperatingMode;
  label: string;
  /** Tailwind classes using semantic-neutral status colours. */
  className: string;
  enabled: boolean;
  detail: string;
}

export const OPERATING_MODES: Record<OperatingMode, OperatingModeMeta> = {
  SIMULATED: {
    mode: 'SIMULATED',
    label: 'Simulated',
    className: 'v2-badge-simulated',
    enabled: CAPABILITIES.simulatedMode.enabled,
    detail: 'Deterministic AURA DC simulation with synthetic inputs.',
  },
  REPLAYED: {
    mode: 'REPLAYED',
    label: 'Replayed',
    className: 'v2-badge-demo',
    enabled: CAPABILITIES.replayedMode.enabled,
    detail: 'Disabled until a validated recorded dataset is proven.',
  },
  LIVE: {
    mode: 'LIVE',
    label: 'Live',
    className: 'v2-badge-live',
    enabled: CAPABILITIES.liveTelemetry.enabled,
    detail: 'Disabled until a facility telemetry source is verified.',
  },
  NVIDIA_DSX: {
    mode: 'NVIDIA_DSX',
    label: 'NVIDIA DSX',
    className: 'v2-badge-not-assessed',
    enabled: CAPABILITIES.nvidiaRuntime.enabled && CAPABILITIES.dsxExchange.enabled,
    detail: 'Blocked by infrastructure: GPU runner, entitlements and DSX Exchange distribution required.',
  },
};

export const ACTIVE_MODE: OperatingMode = 'SIMULATED';

export const INPUT_CLASSIFICATION = 'Synthetic inputs';

export const SIMULATION_SOURCE = 'AURA deterministic simulation';

export const EVIDENCE_BOUNDARY_PREFIX = 'Based on simulation run';

/**
 * Deterministic run-id formatter used by the simulation execution lifecycle
 * when a new run is started. It must NOT be called during rendering: display
 * surfaces read the persisted run id via `useRunProvenance()` instead.
 */
export function simulationRunId(now: Date = new Date()): string {
  const iso = now.toISOString().slice(0, 10);
  return `SIM-${iso}-001`;
}

export function activeScenarioLabel(): string {
  // "Design baseline" states what the values are: the modelled design point,
  // not an operating facility.
  return 'Design baseline';
}

export function evidenceBoundaryNotice(runId?: string | null): string {
  if (!runId) {
    return 'No simulation run has been recorded yet, so no result provenance is available. No live facility or NVIDIA DSX data was used.';
  }
  return `${EVIDENCE_BOUNDARY_PREFIX} ${runId}. No live facility or NVIDIA DSX data was used.`;
}

export const OPERATING_STATE_TOOLTIP =
  'Values are generated by a deterministic AURA DC simulation. No live facility or NVIDIA DSX data is being used.';
