/**
 * Operating state shared by the persistent state bar, provenance drawers
 * and exports. Mode truth comes from the capability registry.
 */
import { CAPABILITIES } from './registry';

export type OperatingMode = 'SIMULATED' | 'REPLAYED' | 'LIVE' | 'NVIDIA_DSX';

export interface OperatingModeMeta {
  mode: OperatingMode;
  label: string;
  /** Tailwind classes using semantic-neutral status colours. */
  className: string;
  enabled: boolean;
  detail: string;
}

export const OPERATING_MODES: Record<OperatingMode, OperatingModeMeta> = {
  SIMULATED: {
    mode: 'SIMULATED',
    label: 'Simulated',
    className: 'border-violet-500/40 bg-violet-500/10 text-violet-700 dark:text-violet-300',
    enabled: CAPABILITIES.simulatedMode.enabled,
    detail: 'Deterministic AURA DC simulation with synthetic inputs.',
  },
  REPLAYED: {
    mode: 'REPLAYED',
    label: 'Replayed',
    className: 'border-blue-500/40 bg-blue-500/10 text-blue-700 dark:text-blue-300',
    enabled: CAPABILITIES.replayedMode.enabled,
    detail: 'Disabled until a validated recorded dataset is proven.',
  },
  LIVE: {
    mode: 'LIVE',
    label: 'Live',
    className: 'border-emerald-500/40 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300',
    enabled: CAPABILITIES.liveTelemetry.enabled,
    detail: 'Disabled until a facility telemetry source is verified.',
  },
  NVIDIA_DSX: {
    mode: 'NVIDIA_DSX',
    label: 'NVIDIA DSX',
    className: 'border-border bg-muted text-muted-foreground',
    enabled: CAPABILITIES.nvidiaRuntime.enabled && CAPABILITIES.dsxExchange.enabled,
    detail: 'Blocked by infrastructure: GPU runner, entitlements and DSX Exchange distribution required.',
  },
};

export const ACTIVE_MODE: OperatingMode = 'SIMULATED';

export const INPUT_CLASSIFICATION = 'Synthetic inputs';

export const SIMULATION_SOURCE = 'AURA deterministic simulation';

export const EVIDENCE_BOUNDARY_PREFIX = 'Based on simulation run';

/** Deterministic run id: SIM-YYYY-MM-DD-001 for the given day. */
export function simulationRunId(now: Date = new Date()): string {
  const iso = now.toISOString().slice(0, 10);
  return `SIM-${iso}-001`;
}

export function activeScenarioLabel(): string {
  return 'Baseline Operations';
}

export function evidenceBoundaryNotice(runId: string = simulationRunId()): string {
  return `${EVIDENCE_BOUNDARY_PREFIX} ${runId}. No live facility or NVIDIA DSX data was used.`;
}

export const OPERATING_STATE_TOOLTIP =
  'Values are generated by a deterministic AURA DC simulation. No live facility or NVIDIA DSX data is being used.';
