import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
import { signalStrength, SIGNAL_BASIS } from '@/capabilities/recommendationSignal';
  FileText, 
  Link as LinkIcon, 
  CheckCircle2, 
  Clock,
  ExternalLink,
  Eye,
} from "lucide-react";

interface GeminiResponsePanelProps {
  className?: string;
}

export function GeminiResponsePanel({ className }: GeminiResponsePanelProps) {
  const snippets = [
    {
      doc: "HIPAA-Security-2025.pdf",
      section: "5.2 - Authentication Requirements",
      text: "All patient portal access must implement two-factor authentication (2FA) using either SMS, authenticator apps, or hardware tokens...",
      score: 0.92,
    },
    {
      doc: "HIPAA-Privacy-Rules.pdf",
      section: "3.4 - Data Access Controls",
      text: "Healthcare providers must maintain audit logs of all patient data access for a minimum of 7 years...",
      score: 0.88,
    },
    {
      doc: "HIPAA-Compliance-Guide.pdf",
      section: "8.1 - 2025 Updates Summary",
      text: "The 2025 HIPAA update introduces mandatory encryption for patient communications and enhanced breach notification timelines...",
      score: 0.85,
    },
  ];

  const citations = [
    { ref: "[1]", doc: "HIPAA-Security-2025.pdf", section: "5.2", confidence: 92 },
    { ref: "[2]", doc: "HIPAA-Privacy-Rules.pdf", section: "3.4", confidence: 88 },
    { ref: "[3]", doc: "HIPAA-Compliance-Guide.pdf", section: "8.1", confidence: 85 },
  ];

  return (
    <Card className={`glass-panel p-6 ${className}`}>
      <Tabs defaultValue="answer" className="w-full">
        <TabsList className="bg-muted border border-border mb-4">
          <TabsTrigger value="answer">Answer</TabsTrigger>
          <TabsTrigger value="snippets">Snippets (3)</TabsTrigger>
          <TabsTrigger value="citations">Citations</TabsTrigger>
        </TabsList>

        {/* Answer Tab */}
        <TabsContent value="answer" className="space-y-4">
          <div className="flex items-start justify-between mb-4">
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
                <FileText className="h-4 w-4 text-primary-foreground" />
              </div>
              <div>
                <p className="font-semibold text-sm">Grounded Answer</p>
                <p className="text-xs text-muted-foreground">
                  Generated by Gemini 1.5 Pro
                </p>
              </div>
            </div>
            <Badge variant="outline" className="border-secondary text-secondary">
              <CheckCircle2 className="h-3 w-3 mr-1" />
              Verified
            </Badge>
          </div>

          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p className="text-sm leading-relaxed">
              The 2025 HIPAA update introduces several key changes to enhance
              patient data security. Most notably, it adds{" "}
              <span className="font-semibold text-primary">
                mandatory two-factor authentication
              </span>{" "}
              (2FA) for all patient portals{" "}
              <sup className="text-primary cursor-pointer hover:underline">
                [1]
              </sup>
              . Healthcare providers must now implement 2FA using SMS,
              authenticator apps, or hardware tokens.
            </p>
            <p className="text-sm leading-relaxed mt-3">
              Additionally, the update mandates enhanced audit logging, requiring
              providers to maintain records of patient data access for a minimum
              of 7 years{" "}
              <sup className="text-primary cursor-pointer hover:underline">
                [2]
              </sup>
              . The update also introduces mandatory encryption for all patient
              communications and shortened breach notification timelines{" "}
              <sup className="text-primary cursor-pointer hover:underline">
                [3]
              </sup>
              .
            </p>
          </div>

          {/* Metadata */}
          <div className="pt-4 border-t border-border grid grid-cols-3 gap-4 text-xs">
            <div>
              <p className="text-muted-foreground mb-1">Generation Time</p>
              <div className="flex items-center gap-1">
                <Clock className="h-3 w-3 text-secondary" />
                <span className="font-mono font-semibold">2.3s</span>
              </div>
            </div>
            <div>
              <p className="text-muted-foreground mb-1">Context Tokens</p>
              <span className="font-mono font-semibold">1,847</span>
            </div>
            <div>
              <p className="text-muted-foreground mb-1">Faithfulness Score</p>
              <span className="font-mono font-semibold text-secondary">88%</span>
            </div>
          </div>
        </TabsContent>

        {/* Snippets Tab */}
        <TabsContent value="snippets" className="space-y-3">
          {snippets.map((snippet, idx) => (
            <div
              key={idx}
              className="p-4 rounded-lg border border-border hover:border-secondary/50 transition-smooth"
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <FileText className="h-4 w-4 text-primary" />
                    <span className="font-semibold text-sm">{snippet.doc}</span>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Section {snippet.section}
                  </p>
                </div>
                <div className="flex flex-col items-end gap-1">
                  <Badge variant="outline" className="text-xs border-secondary text-secondary">
                    {Math.round(snippet.score * 100)}% match
                  </Badge>
                </div>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {snippet.text}
              </p>
              <Button variant="ghost" size="sm" className="mt-2 h-7 text-xs">
                <Eye className="h-3 w-3 mr-1" />
                View Full Document
              </Button>
            </div>
          ))}
        </TabsContent>

        {/* Citations Tab */}
        <TabsContent value="citations" className="space-y-3">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-2 text-xs font-semibold text-muted-foreground">
                    Ref
                  </th>
                  <th className="text-left py-2 text-xs font-semibold text-muted-foreground">
                    Document
                  </th>
                  <th className="text-left py-2 text-xs font-semibold text-muted-foreground">
                    Section
                  </th>
                  <th className="text-left py-2 text-xs font-semibold text-muted-foreground">
                    Confidence
                  </th>
                  <th className="text-right py-2 text-xs font-semibold text-muted-foreground">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody>
                {citations.map((citation, idx) => (
                  <tr key={idx} className="border-b border-border/50 hover:bg-muted/30 transition-smooth">
                    <td className="py-3">
                      <span className="font-mono text-sm font-bold text-primary">
                        {citation.ref}
                      </span>
                    </td>
                    <td className="py-3">
                      <span className="text-sm">{citation.doc}</span>
                    </td>
                    <td className="py-3">
                      <span className="text-sm text-muted-foreground">
                        {citation.section}
                      </span>
                    </td>
                    <td className="py-3">
                      <span className="font-mono text-sm font-semibold text-secondary">
                        {signalStrength(citation.confidence)}
                      </span>
                    </td>
                    <td className="py-3 text-right">
                      <Button variant="ghost" size="sm" className="h-7">
                        <ExternalLink className="h-3 w-3" />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="pt-4 border-t border-border">
            <p className="text-xs text-muted-foreground mb-2">
              All citations verified through Vertex AI Grounding
            </p>
            <Button variant="outline" size="sm">
              <LinkIcon className="h-3 w-3 mr-2" />
              Export Citation List
            </Button>
          </div>
        </TabsContent>
      </Tabs>
    </Card>
  );
}
