/**
 * Studio Screenshots Manifest
 * Maps landing page assets to screenshot file paths
 * Auto-generated by screenshot pipeline
 */

export interface ScreenshotVariants {
  desktop: string;
  tablet?: string;
  mobile?: string;
  alt: string;
  title: string;
}

export interface StudioScreenshotsManifest {
  version: string;
  generatedAt: string;
  screenshots: Record<string, ScreenshotVariants>;
}

// Generated screenshot paths - these are actual Studio UI captures
export const studioScreenshots: Record<string, ScreenshotVariants> = {
  dashboard: {
    desktop: '/landing/screenshots/dashboard-desktop.webp',
    tablet: '/landing/screenshots/dashboard-tablet.webp',
    mobile: '/landing/screenshots/dashboard-mobile.webp',
    alt: 'M2M AURA Dashboard showing live Digital Twin preview with real-time KPIs',
    title: 'Dashboard Overview',
  },
  blueprint: {
    desktop: '/landing/screenshots/blueprint-desktop.webp',
    tablet: '/landing/screenshots/blueprint-tablet.webp',
    mobile: '/landing/screenshots/blueprint-mobile.webp',
    alt: 'Blueprint Designer interface for configuring Data Centre Twin architecture',
    title: 'Blueprint Designer',
  },
  simulation: {
    desktop: '/landing/screenshots/simulation-desktop.webp',
    tablet: '/landing/screenshots/simulation-tablet.webp',
    mobile: '/landing/screenshots/simulation-mobile.webp',
    alt: 'Simulation panel with timeline controls and KPI trend overlays',
    title: 'Scenario Simulation',
  },
  twin3d: {
    desktop: '/landing/screenshots/twin3d-desktop.webp',
    tablet: '/landing/screenshots/twin3d-tablet.webp',
    mobile: '/landing/screenshots/twin3d-mobile.webp',
    alt: '3D Data Centre visualization with thermal heatmaps and rack layouts',
    title: '3D Digital Twin',
  },
  agents: {
    desktop: '/landing/screenshots/agents-desktop.webp',
    tablet: '/landing/screenshots/agents-tablet.webp',
    mobile: '/landing/screenshots/agents-mobile.webp',
    alt: 'Subsystem Agents dashboard showing AI optimization agents',
    title: 'Subsystem Agents',
  },
  sovereignty: {
    desktop: '/landing/screenshots/sovereignty-desktop.webp',
    tablet: '/landing/screenshots/sovereignty-tablet.webp',
    mobile: '/landing/screenshots/sovereignty-mobile.webp',
    alt: 'Sovereignty and Safety Audit dashboard with compliance metrics',
    title: 'Sovereignty & Safety',
  },
  telemetry: {
    desktop: '/landing/screenshots/telemetry-desktop.webp',
    tablet: '/landing/screenshots/telemetry-tablet.webp',
    mobile: '/landing/screenshots/telemetry-mobile.webp',
    alt: 'Telemetry and Analytics panel with real-time KPI monitoring',
    title: 'Telemetry & Analytics',
  },
  recommendation: {
    desktop: '/landing/screenshots/recommendation-desktop.webp',
    tablet: '/landing/screenshots/recommendation-tablet.webp',
    mobile: '/landing/screenshots/recommendation-mobile.webp',
    alt: 'AI-powered Green DC Twin recommendation panel',
    title: 'Smart Recommendations',
  },
};

// Manifest metadata
export const screenshotManifest: StudioScreenshotsManifest = {
  version: '1.0.0',
  generatedAt: new Date().toISOString(),
  screenshots: studioScreenshots,
};

// Helper to get screenshot with fallback
export const getScreenshot = (
  key: keyof typeof studioScreenshots,
  variant: 'desktop' | 'tablet' | 'mobile' = 'desktop'
): string => {
  const screenshot = studioScreenshots[key];
  if (!screenshot) {
    console.warn(`Screenshot not found for key: ${key}`);
    return '/placeholder.svg';
  }
  return screenshot[variant] || screenshot.desktop;
};

// Check if screenshot exists (for fallback logic)
export const screenshotExists = async (path: string): Promise<boolean> => {
  try {
    const response = await fetch(path, { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
};
